#!/usr/bin/env python3
"""Generate brand SVGs; optionally export PNGs using Node + sharp (see assets/README.md)."""

from __future__ import annotations

import argparse
import html
import json
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[1]
BLUE, INK, MUTED, LINE = "#2563eb", "#0f172a", "#526077", "#dbe3f0"
FONT = "Inter, Helvetica Neue, Helvetica, Arial, sans-serif"


def svg(width: int, height: int, title: str, content: str) -> str:
    return (f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
            f'viewBox="0 0 {width} {height}" role="img" aria-labelledby="title">\n'
            f'<title id="title">{html.escape(title)}</title>\n'
            '<!-- Generated by scripts/build-brand-assets.py. -->\n'
            f'{content}\n</svg>\n')


def text(x, y, value, size, color=INK, weight=400, spacing=0, anchor="start"):
    return (f'<text x="{x}" y="{y}" font-family="{FONT}" font-size="{size}" '
            f'font-weight="{weight}" letter-spacing="{spacing}" fill="{color}" '
            f'text-anchor="{anchor}">{html.escape(value)}</text>')


def mark(x=0, y=0, size=512):
    """Cloud silhouette, sprout cutout, seed; readable at favicon sizes."""
    return f'''<g transform="translate({x} {y}) scale({size / 512:g})">
<rect width="512" height="512" rx="112" fill="{BLUE}"/>
<path d="M154 328C115 328 86 301 86 264C86 225 114 195 152 192C163 142 205 108 258 108C320 108 371 149 381 209C414 217 436 245 436 279C436 307 413 328 382 328Z" fill="#fff"/>
<path d="M256 328V262" fill="none" stroke="{BLUE}" stroke-width="22" stroke-linecap="round"/>
<path d="M256 283C222 283 197 261 194 231C225 229 253 248 256 283ZM256 265C254 234 276 210 308 206C309 236 288 261 256 265Z" fill="{BLUE}"/>
<circle cx="256" cy="380" r="19" fill="#fff"/>
</g>'''


def wordmark(dark=False):
    ink, muted = ("#f8fafc", "#c3cee0") if dark else (INK, MUTED)
    return svg(720, 160, "cloudseed — Your cloud. A stronger foundation.", "\n".join([
        mark(8, 8, 144), text(182, 87, "cloudseed", 68, ink, 700, -2.8),
        text(184, 127, "Your cloud. A stronger foundation.", 23, muted),
    ]))


def card(width, height):
    gx = width - 432
    parts = [
        f'<rect width="{width}" height="{height}" fill="#fff"/>',
        f'<rect width="{width}" height="8" fill="{BLUE}"/>',
        mark(64, 49, 48), text(127, 84, "cloudseed", 34, weight=700, spacing=-1.3),
        text(width - 64, 80, "OPEN SOURCE INFRASTRUCTURE", 13, MUTED, 600, 1.7, "end"),
        text(64, 235, "Your cloud.", 76, weight=700, spacing=-3.5),
        text(64, 321, "A stronger", 76, BLUE, 700, -3.5),
        text(64, 407, "foundation.", 76, BLUE, 700, -3.5),
        text(68, 474, "Private landing zones. Kubernetes platforms.", 23, MUTED),
        f'<rect x="{gx}" y="171" width="368" height="318" rx="20" fill="#f5f8ff"/>',
        f'<rect x="{gx + 20}" y="191" width="328" height="278" rx="12" fill="none" stroke="{LINE}" stroke-dasharray="4 6"/>',
        mark(gx + 114, 210, 140),
        f'<path d="M{gx + 184} 350V376M{gx + 70} 399V376H{gx + 298}V399M{gx + 184} 376V399" fill="none" stroke="#94b4f5" stroke-width="2"/>',
    ]
    for dx, label in [(28, "Network"), (142, "Access"), (256, "Platform")]:
        parts += [f'<rect x="{gx + dx}" y="399" width="84" height="44" rx="8" fill="#fff" stroke="#c5d5f5"/>',
                  text(gx + dx + 42, 427, label, 15, INK, 600, anchor="middle")]
    parts += [f'<path d="M64 {height - 101}H{width - 64}" stroke="{LINE}"/>',
              text(64, height - 50, "AWS", 18, weight=600),
              text(147, height - 50, "Google Cloud", 18, weight=600),
              text(309, height - 50, "Azure", 18, weight=600),
              text(405, height - 50, "VMware", 18, weight=600),
              text(width - 64, height - 50, "nimeshbuilds.github.io/cloudseed", 16, MUTED, anchor="end")]
    return svg(width, height, "cloudseed — Your cloud. A stronger foundation. AWS, Google Cloud, Azure, VMware.", "\n".join(parts))


def generate():
    icon, social = svg(512, 512, "cloudseed cloud and seed icon", mark()), card(1200, 630)
    files = {"assets/icon.svg": icon, "assets/logo.svg": wordmark(),
             "assets/logo-dark.svg": wordmark(True), "assets/banner.svg": card(1280, 640),
             "assets/social-preview.svg": social, "docs/assets/icon.svg": icon,
             "docs/assets/og-image.svg": social}
    for name, content in files.items():
        (ROOT / name).write_text(content, encoding="utf-8")
    return [(str(ROOT / src), str(ROOT / dest), w, h) for src, dest, w, h in [
        ("assets/icon.svg", "assets/icon.png", 1024, 1024),
        ("assets/logo.svg", "assets/logo.png", 1440, 320),
        ("assets/logo-dark.svg", "assets/logo-dark.png", 1440, 320),
        ("assets/banner.svg", "assets/banner.png", 1280, 640),
        ("assets/social-preview.svg", "assets/social-preview.png", 1200, 630),
        ("docs/assets/icon.svg", "docs/assets/favicon.png", 48, 48),
        ("docs/assets/icon.svg", "docs/assets/apple-touch-icon.png", 180, 180),
        ("docs/assets/og-image.svg", "docs/assets/og-image.png", 1200, 630),
    ]]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--png", action="store_true", help="also export PNGs with optional sharp renderer")
    parser.add_argument("--node", default="node", help="Node executable")
    parser.add_argument("--sharp-module", default="sharp", help="sharp module name or absolute package directory")
    args = parser.parse_args()
    exports = generate()
    print("Wrote 7 SVG assets.")
    if args.png:
        script = r'''
const fs = require("node:fs");
const sharp = require(process.argv[1]);
const exports = JSON.parse(fs.readFileSync(0, "utf8"));
(async () => {
  for (const [src, dest, width, height] of exports) {
    await sharp(src, { density: 192 }).resize(width, height).png().toFile(dest);
  }
})().catch(error => { console.error(error.message); process.exit(1); });
'''
        subprocess.run([args.node, "-e", script, args.sharp_module], input=json.dumps(exports), text=True, check=True)
        print(f"Wrote {len(exports)} PNG assets.")
    else:
        print("PNG exports unchanged; pass --png after installing the optional sharp renderer.")


if __name__ == "__main__":
    main()
