#!/usr/bin/env python3
"""Generate docs/reference/*.md from cloudseed's own data, so the reference can never drift from the code.

    python3 scripts/gen-docs.py            write the pages (only files whose content changed are rewritten)
    python3 scripts/gen-docs.py --check    exit 1 when a page is missing or out of date (CI)

Sources: the help pages (cloudseed/help.py), the Terraform variables and outputs of every target (terraform/<cloud>),
the target skills (skills/cloudseed-<cloud>/SKILL.md), the platform catalog (cloudseed/platform.py), the MCP server's
tools, resources and prompts (cloudseed/mcp.py), the explain index (cloudseed/explain.py) and the bundled skills.

Standard library only, no ANSI, stable ordering, no timestamps: running it twice gives byte-identical files.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "reference"
SITE = "https://nimeshbuilds.github.io/cloudseed/"
REPO = "https://github.com/nimeshbuilds/cloudseed"

# ---------------------------------------------------------------- a clean, deterministic import of cloudseed
# Nothing from the machine that runs this may leak into the pages: a private home, no cloud / agent variables, no
# terminal width, no colour.
_SCRATCH = tempfile.mkdtemp(prefix="cloudseed-gen-docs-")
for _k in list(os.environ):
    if _k.startswith(("AWS_", "GOOGLE_", "CLOUDSDK_", "GCLOUD_", "ARM_", "AZURE_", "CLOUDSEED_", "VMREST_", "VMWARE_")):
        del os.environ[_k]
os.environ.update({"CLOUDSEED_HOME": str(Path(_SCRATCH) / "cloudseed"), "NO_COLOR": "1", "COLUMNS": "100",
                   "CLOUDSEED_NONINTERACTIVE": "1", "TERM": "dumb"})
sys.path.insert(0, str(ROOT))

from cloudseed import __version__, help as helpmod, paths, platform as pl  # noqa: E402

CLOUDS = tuple(helpmod.CLOUDS)
CLOUD_NAMES = {"aws": "AWS", "gcp": "Google Cloud", "azure": "Azure", "vmware": "VMware (local)"}
SKILL_OF = {"aws": "cloudseed-aws", "gcp": "cloudseed-gcp", "azure": "cloudseed-azure", "vmware": "cloudseed-vmware"}


# ---------------------------------------------------------------- markdown helpers
def _scrub(text: str) -> str:
    """Machine-specific paths out of generated text: the private home becomes ~/.cloudseed, the checkout <repo>."""
    text = text.replace(str(paths.HOME), "~/.cloudseed")
    text = text.replace(str(paths.REPO_ROOT), "<repo>")
    return text


def esc(text: str) -> str:
    """Prose for a markdown paragraph or table cell: code spans are kept, everything else is escaped so that
    placeholders (<cloud>), pipes and asterisks render as written."""
    out = []
    for i, part in enumerate(re.split(r"(`[^`\n]+`)", str(text))):
        if i % 2:                       # a code span
            out.append(part.replace("|", "&#124;") if "|" in part else part)
            continue
        part = part.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("|", "&#124;")
        part = part.replace("*", r"\*").replace("_", r"\_").replace("[", r"\[")
        out.append(part)
    return " ".join("".join(out).split())


def code(text: str) -> str:
    """A value as inline code (a table cell): backticks cannot hold a pipe or a backtick, so those fall back to text."""
    text = " ".join(str(text).split())
    if not text:
        return "–"
    if "`" in text or "|" in text:
        return esc(text)
    return f"`{text}`"


def fence(text: str, lang: str = "text") -> str:
    body = "\n".join(line.rstrip() for line in text.strip("\n").splitlines())
    return f"```{lang}\n{body}\n```"


def front(title: str, description: str) -> str:
    # JSON strings are valid YAML double-quoted scalars: a description with ": " or "#" stays one string
    return (f"---\ntitle: {json.dumps(title, ensure_ascii=False)}\n"
            f"description: {json.dumps(description, ensure_ascii=False)}\n---\n\n"
            f"<!-- Generated by scripts/gen-docs.py from cloudseed {__version__}. Do not edit: run "
            "`python3 scripts/gen-docs.py` instead. -->\n\n")


def generated_note(source: str) -> str:
    return (f'!!! info "Generated from the code"\n    This page is generated by `scripts/gen-docs.py` from {source}, so '
            f"it always matches the CLI you install (this build: cloudseed {__version__}).\n")


# ---------------------------------------------------------------- help pages -> markdown
_HEADER_RE = re.compile(r"^[A-Z][A-Z0-9 &/<>,.'()-]{3,}$")


def _is_header(line: str) -> bool:
    s = line.rstrip()
    return bool(s) and not s.startswith(" ") and bool(_HEADER_RE.match(s)) and any(c.isalpha() for c in s) and s.upper() == s


def _title_case(header: str) -> str:
    words = header.strip().split()
    keep = {"AWS", "GCP", "VMWARE", "FIPS", "CLI", "MCP", "UI", "UIS", "VPN", "SSH", "DR", "CIS", "STIG", "TLS", "API", "CI"}
    fixed = []
    for i, w in enumerate(words):
        bare = re.sub(r"[^A-Z]", "", w)
        if bare in keep:
            fixed.append({"VMWARE": "VMware", "UIS": "UIs"}.get(bare, w))
        else:
            fixed.append(w.lower() if i else w.capitalize())
    return " ".join(fixed)


def help_body(text: str, level: str = "###") -> tuple[str, list[str]]:
    """A help page (without its synopsis) as markdown: UPPER-CASE lines become headings, prose at column 0 becomes
    paragraphs, indented blocks stay preformatted. The EXAMPLES section is returned separately (runnable commands)."""
    lines = _scrub(text).splitlines()
    examples: list[str] = []
    if "EXAMPLES" in [l.strip() for l in lines]:
        i = [l.strip() for l in lines].index("EXAMPLES")
        examples = [l.rstrip() for l in lines[i + 1:] if l.strip()]
        lines = lines[:i]
    out: list[str] = []
    pre: list[str] = []
    prose: list[str] = []

    def flush() -> None:
        if prose:
            out.append(esc(" ".join(prose)))
            out.append("")
            prose.clear()
        if pre:
            out.append(fence("\n".join(pre)))
            out.append("")
            pre.clear()

    for line in lines:
        if not line.strip():
            if pre:
                pre.append("")
            else:
                flush()
            continue
        if _is_header(line):
            flush()
            out += [f"{level} {esc(_title_case(line))}", ""]
            continue
        if line.startswith(" "):
            if prose:
                flush()
            pre.append(line)
        else:
            if pre:
                flush()
            prose.append(line.strip())
    flush()
    while out and not out[-1]:
        out.pop()
    return "\n".join(out), examples


def split_synopsis(text: str) -> tuple[str, str]:
    text = _scrub(text).strip("\n")
    parts = text.split("\n\n", 1)
    return parts[0], parts[1] if len(parts) > 1 else ""


def _overview_table() -> list[tuple[list[str], bool, str]]:
    """The command tables of the help overview as rows (commands, primary, description), in order."""
    rows: list[tuple[list[str], bool, str]] = []    # (commands, primary, description)
    section = ""
    for line in helpmod.OVERVIEW.splitlines():
        if line and not line.startswith(" "):
            section = line.strip()
            continue
        if not any(s in section for s in ("COMMANDS", "INSTALL", "INTEGRATIONS")):
            continue
        m = re.match(r"^  (\S(?:.*?\S)?)\s{2,}(\S.*)$", line)
        if m and not line.startswith("   "):
            tokens = [t for t in re.split(r"\s+", m.group(1).replace(" | ", "|")) if t]
            head = [w for w in tokens[0].split("|") if re.match(r"^[a-z][a-z0-9-]*$", w)]
            primary = all(t.startswith(("<", "[", '"')) for t in tokens[1:])
            rows.append((head, primary, m.group(2).strip()))
            continue
        cont = re.match(r"^ {10,}(\S.*)$", line)
        if cont and rows:
            words, primary, desc = rows[-1]
            rows[-1] = (words, primary, desc + " " + cont.group(1).strip())
    return rows


def _usage_rows() -> dict[str, str]:
    """command word -> description from the USAGE block of the help overview (`cloudseed help [command | topic]  this
    help, ...`): the lowest-priority source, for commands the command tables do not describe."""
    out: dict[str, str] = {}
    section = ""
    for line in helpmod.OVERVIEW.splitlines():
        if line and not line.startswith(" "):
            section = line.strip()
            continue
        m = re.match(r"^  cloudseed ([a-z][a-z0-9-]*)\b.*?\s{2,}(\S.*)$", line) if section.startswith("USAGE") else None
        if m:
            out.setdefault(m.group(1), m.group(2).strip())
    return out


def overview_rows() -> dict[str, str]:
    """command word -> one-line description, from the command tables of the help overview (the text `cloudseed help`
    prints). A row naming the command alone (`setup <cloud>`, `kubectl|helm|k9s`, `enable | disable`) wins over a row
    about one of its subcommands (`enable ui`, `setup mcp`), which only fills in a command that has no row of its own:
    the parent's (`enable`), or a command named by its second word (`enable ui` describes `ui`). The USAGE block comes
    last (`cloudseed help ...`)."""
    rows = _overview_table()
    out: dict[str, str] = {}
    for want_primary in (True, False):
        for words, primary, desc in rows:
            if primary == want_primary:
                for w in words:
                    out.setdefault(w, desc)
    for line in helpmod.OVERVIEW.splitlines():     # `enable ui   the local web console ...` -> ui
        m = re.match(r"^  ([a-z][a-z0-9-]*) ([a-z][a-z0-9-]*)\s{2,}(\S.*)$", line)
        if m and m.group(2) in helpmod.COMMANDS:
            out.setdefault(m.group(2), m.group(3).strip())
    for w, desc in _usage_rows().items():
        out.setdefault(w, desc)
    return out


def command_order() -> list[str]:
    seen: list[str] = []
    for w in [w for words, _, _ in _overview_table() for w in words]:
        page = helpmod.ALIASES.get(w, w)
        if page in helpmod.COMMANDS and page not in seen:
            seen.append(page)
    rest = sorted(c for c in helpmod.COMMANDS if c not in helpmod.ALIASES and c not in seen)
    return seen + rest


_TITLES = {"managed": "databricks / snowflake", "kubectl": "kubectl / helm / k9s"}


def _command_desc(c: str, rows: dict[str, str], aliases: dict[str, list[str]]) -> str:
    """The overview's description of a help page: its own row, else the rows of the words that open it (`databricks`
    and `snowflake` share the `managed` page: both descriptions, joined)."""
    if rows.get(c):
        return rows[c]
    descs: list[str] = []
    for a in aliases.get(c, []):
        if rows.get(a) and rows[a] not in descs:
            descs.append(rows[a])
    return "; ".join(descs)


def page_commands() -> str:
    rows = overview_rows()
    aliases: dict[str, list[str]] = {}
    for a, target in sorted(helpmod.ALIASES.items()):
        aliases.setdefault(target, []).append(a)
    out = [front("CLI command reference", "Every cloudseed command with its options and examples, generated from "
                 "cloudseed's own help pages: setup, destroy, platform, dr, chaos, scan, undo, mcp, ui and more."),
           "# CLI command reference", "",
           "Every `cloudseed` command (`cs` is the short alias) with its synopsis, options and runnable examples. "
           "This is the text `cloudseed help <command>` prints, laid out for the web.", "",
           generated_note("the CLI's help pages (`cloudseed/help.py`)"),
           "## Overview", "", "The page `cloudseed help` (or just `cloudseed`) prints:", "",
           fence(_scrub(helpmod.OVERVIEW)), ""]
    order = command_order()
    out += ["## Commands at a glance", "", "| Command | What it does |", "|---|---|"]
    for c in order:
        title = _TITLES.get(c, c)
        desc = _command_desc(c, rows, aliases)
        out.append(f"| [`cloudseed {title}`](#{_slug('cloudseed ' + title)}) | {esc(desc)} |")
    out.append("")
    for c in order:
        title = _TITLES.get(c, c)
        out += [f"## cloudseed {title}", ""]
        desc = _command_desc(c, rows, aliases)
        if desc:
            out += [esc(desc[:1].upper() + desc[1:]), ""]
        also = [a for a in aliases.get(c, []) if a not in title.split(" / ")]
        if also:
            out += ["Also: " + ", ".join(f"`cloudseed {a}`" for a in also) + " (same page).", ""]
        synopsis, body = split_synopsis(helpmod.page(c))
        out += [fence(synopsis), ""]
        md, examples = help_body(body)
        if md:
            out += [md, ""]
        if examples:
            out += ["**Examples**", "", fence("\n".join(e.strip() if not e.startswith("    ") else e[2:] for e in examples), "bash"), ""]
        out += [f"Terminal: `cloudseed help {c if c != 'managed' else 'databricks'}` · How it works: "
                f"`cloudseed explain command {c if c != 'managed' else 'databricks'}`", ""]
    return "\n".join(out).rstrip() + "\n"


def _slug(text: str) -> str:
    """The anchor MkDocs' toc extension gives a heading (default slugify)."""
    text = re.sub(r"[^\w\s-]", "", text.lower()).strip()
    return re.sub(r"[-\s]+", "-", text)


def _topic_order() -> list[str]:
    """The topics that are not also commands, in the order the help overview lists them (its TOPICS line), then any
    other topic alphabetically."""
    listed: list[str] = []
    m = re.search(r"^TOPICS.*?\n((?:  .*\n?)+)", helpmod.OVERVIEW, re.M)
    if m:
        listed = [w for w in re.findall(r"[a-z][a-z0-9-]*", m.group(1).split("(")[0])]
    topics = [t for t in helpmod.TOPICS if t not in helpmod.COMMANDS]
    return [t for t in listed if t in topics] + sorted(t for t in topics if t not in listed)


def _topic_parts(t: str) -> tuple[str, str, str]:
    """(heading, markdown note, body text) of a help topic. Its first line is its title: all capitals
    (`QUICKSTART`), or capitals and an aside in parentheses (`FIPS 140 MODE  (cloudseed setup ... fips_mode=true)`),
    which becomes the note. A topic without a title line is headed by its name."""
    text = _scrub(helpmod.page(t)).strip("\n")
    first, _, rest = text.partition("\n")
    titled = re.match(r"^([A-Z][A-Z0-9 &/,.'-]*[A-Z0-9])\s+\((.+)\)$", first.strip())
    if _is_header(first):
        return _title_case(first), "", rest
    if titled:
        aside = titled.group(2).strip()
        note = f"`{aside}`" if aside.startswith("cloudseed ") and "`" not in aside else \
            esc(aside[:1].upper() + aside[1:] + ("" if aside.endswith(".") else "."))
        return _title_case(titled.group(1)), note, rest
    return _title_case(t.upper()), "", text


def page_topics() -> str:
    out = [front("Help topics", "cloudseed's built-in help topics - quickstart, security model, Terraform state, "
                 "environments, local VMware VMs, optional services, FIPS 140 mode, troubleshooting and examples."),
           "# Help topics", "",
           "The guides built into the CLI (`cloudseed help <topic>`). Topics that share a name with a command "
           "(`deps`, `agentic`, `destroy`) are part of that command's page in the "
           "[command reference](commands.md).", "", generated_note("the CLI's help topics (`cloudseed/help.py`)")]
    for t in _topic_order():
        heading, note, rest = _topic_parts(t)
        out += [f"## {esc(heading)}", "", f"`cloudseed help {t}`" + (f" · {note}" if note else ""), ""]
        md, examples = help_body(rest)
        if md:
            out += [md, ""]
        if examples:
            out += ["**Examples**", "", fence("\n".join(e.strip() for e in examples), "bash"), ""]
    return "\n".join(out).rstrip() + "\n"


# ---------------------------------------------------------------- targets: skill + variables + outputs
def _skill_parts(cloud: str) -> tuple[str, str, str]:
    """(front-matter description, what-it-builds markdown, gotchas markdown) of skills/cloudseed-<cloud>/SKILL.md."""
    p = ROOT / "skills" / SKILL_OF[cloud] / "SKILL.md"
    if not p.exists():
        return "", "", ""
    text = p.read_text()
    desc = ""
    if text.startswith("---"):
        fm, text = text[3:].split("---", 1)
        m = re.search(r"^description:\s*(.+)$", fm, re.M)
        desc = m.group(1).strip() if m else ""
    sections: dict[str, list[str]] = {"": []}
    cur = ""
    for line in text.strip().splitlines():
        h = re.match(r"^(#{1,6})\s+(.*)$", line)
        if h and len(h.group(1)) == 1:
            continue
        if h and len(h.group(1)) == 2:
            cur = h.group(2).split()[0].lower()
            sections.setdefault(cur, [])
            continue
        if h:                              # deeper headings move one level down under the page's own sections
            line = "#" + line
        sections[cur].append(line)
    body = "\n".join(sections.get("", [])).strip()
    gotchas = "\n".join(sections.get("gotchas", [])).strip()
    return desc, body, gotchas


def _variables(cloud: str) -> tuple[list, list, list]:
    """(stack variables [(name, default, description)], setup inputs [(key, default, sources, description)],
    set by cloudseed [(name, how)]) - the same data and rules as `cloudseed help variables <cloud>`."""
    variables = helpmod._parse_variables(cloud)
    questions = helpmod._cloud_questions(cloud)
    prompts = {q.key: q.prompt for q in questions}
    owned = helpmod._refused_vars(cloud, {n for n, _, _ in variables}, questions)
    computed = dict(helpmod._COMPUTED_DEFAULTS.get(cloud, {}))
    for q in questions:
        if "{sources}" in computed.get(q.key, ""):
            sources = ([helpmod._question_flag(q)] if helpmod._question_flag(q) else []) + list(q.env)
            computed[q.key] = computed[q.key].replace("{sources}", helpmod._or_list(sources) or "an answer")
    stack = []
    for name, desc, default in variables:
        if name in owned:
            continue
        desc = (desc or helpmod._as_statement(prompts.get(name, ""))).replace('\\"', '"')
        stack.append((name, computed.get(name, default), desc))
    declared = {n for n, _, _ in variables}
    inputs = []
    for q in questions:
        if q.key in declared:
            continue
        default = computed.get(q.key) or (helpmod._shown_default(q.default) if not callable(q.default) else "(computed)")
        sources = ([helpmod._question_flag(q)] if helpmod._question_flag(q) else []) + list(q.env)
        choices = helpmod._question_choices(q)
        text = helpmod._as_statement(q.prompt)
        if choices and ", ".join(choices) not in q.prompt:
            text += " - one of: " + ", ".join(choices)
        inputs.append((q.key, default, sources, text))
    managed = [(n, owned[n]) for n, _, _ in variables if n in owned]
    return stack, inputs, managed


def page_target(cloud: str) -> str:
    desc, body, gotchas = _skill_parts(cloud)
    name = CLOUD_NAMES[cloud]
    seo = {"aws": "Terraform AWS landing zone: VPC, NAT, hardened bastion, CloudTrail, GuardDuty, optional EKS - every "
                  "variable and output of cloudseed setup aws.",
           "gcp": "Google Cloud landing zone with Terraform: VPC, Cloud NAT, Shielded VM bastion, optional GKE - every "
                  "variable and output of cloudseed setup gcp.",
           "azure": "Azure landing zone with Terraform: VNet, NSGs, NAT gateway, bastion, Defender, optional AKS - every "
                    "variable and output of cloudseed setup azure.",
           "vmware": "A VMware Fusion / Workstation Kubernetes lab with Terraform: bastion, private VMs, RKE2 or kubeadm "
                     "- every variable and output."}[cloud]
    out = [front(f"{name} target reference", seo), f"# {name} target reference", ""]
    out += [f"What `cloudseed setup {cloud}` builds, every variable you can set with `--var`, and every output. "
            f"In the terminal: `cloudseed help {'vmware-skill' if cloud == 'vmware' else cloud}` or "
            f"`cloudseed explain target {cloud}`.", "",
            generated_note(f"`terraform/{cloud}/variables.tf`, `terraform/{cloud}/outputs.tf`, the setup questions and "
                           f"`skills/{SKILL_OF[cloud]}/SKILL.md`")]
    if body:
        out += ["## What it builds", "", body, ""]
    try:
        stack, inputs, managed = _variables(cloud)
        out += ["## Stack variables", "",
                f"Override any of these with `--var name=value` on `cloudseed setup {cloud}` (JSON for lists and maps; "
                "`--var name=null` drops a saved override). Values are read by the variable's declared type.", "",
                "| Variable | Default | Description |", "|---|---|---|"]
        out += [f"| `{n}` | {code(d)} | {esc(t)} |" for n, d, t in stack]
        out.append("")
        if inputs:
            out += ["## Setup inputs", "", "Asked by `setup` (or given as flags / `--var KEY=VALUE`); they are not "
                    "Terraform variables but shape what is rendered.", "",
                    "| Input | Default | Flag / environment | Description |", "|---|---|---|---|"]
            out += [f"| `{k}` | {code(d)} | {', '.join(code(s) for s in src) or '–'} | {esc(t)} |" for k, d, src, t in inputs]
            out.append("")
        if managed:
            out += ["## Set by cloudseed", "", "These stack variables are refused in `--var`: cloudseed sets them "
                    "itself. Use the flag shown instead.", "", "| Variable | How to set it |", "|---|---|"]
            out += [f"| `{n}` | {esc(how)} |" for n, how in managed]
            out.append("")
    except Exception:  # noqa: BLE001 - the internals moved: fall back to the page the CLI prints
        out += ["## Stack variables", "", fence(_scrub(helpmod.variables_page(cloud))), ""]
    rows = helpmod._parse_outputs(cloud)
    out += ["## Outputs", "", f"Read them with `cloudseed output {cloud} --env <env>` (add `--json` for scripts).", "",
            "| Output | Description |", "|---|---|"]
    out += [f"| `{n}` | {esc(d)} |" for n, d in rows]
    out.append("")
    if gotchas:
        out += ["## Gotchas", "", gotchas, ""]
    return "\n".join(out).rstrip() + "\n"


# ---------------------------------------------------------------- platform catalog
_FIPS_LABEL = {"compatible": "compatible", "tls-restricted": "tls-restricted", "crypto-restricted": "crypto-restricted"}


def _source(spec: dict) -> str:
    m = spec["method"]
    if m in ("helm", "oci"):
        chart = spec["chart"]
        return f"{chart}@{spec['version']}" if spec.get("version") else chart
    if m in ("manifest", "kustomize"):
        return spec.get("url", "")
    if m == "meta":
        return "bundle: " + "; ".join(f"{k} = {', '.join(v)}" for k, v in spec.get("modes", {}).items())
    return "rendered by cloudseed"


def _needs(spec: dict) -> str:
    parts = list(spec.get("needs") or [])
    for t, ds in sorted((spec.get("needs_by_target") or {}).items()):
        parts += [f"{d} ({t})" for d in ds if d not in parts]
    return ", ".join(parts)


def page_platform() -> str:
    visible = {k: v for k, v in pl.CATALOG.items() if not v.get("hidden")}
    shared = getattr(pl, "GROUP_EXTRA_MEMBERS", {})
    out = [front("Platform catalog", f"cloudseed's Kubernetes platform catalog: {len(visible)} pinned Helm items - "
                 "GitOps, observability, Gateway API, data, AI, security, backups and chaos - for EKS, GKE, AKS and RKE2."),
           "# Platform catalog", "",
           f"{len(visible)} curated open-source components in {len(pl.GROUPS)} groups, installed with Helm or kustomize "
           "by `cloudseed platform install <group|item>` with values adapted to the target and distro. Versions are "
           "pinned per cloudseed release; `--version` overrides one item. Dependencies are installed first and never "
           "twice.", "", generated_note("the catalog in `cloudseed/platform.py`"),
           "Legend: **core** items are installed by the group, **extra** items only by name. **FIPS**: *compatible* "
           "items install in a FIPS environment, *tls-restricted* and *crypto-restricted* items install and are "
           "flagged by `cloudseed scan fips`, items marked *no* are refused there unless `--force` "
           "([FIPS 140 mode](../guides/security-and-fips.md)).", "",
           "## Groups", "", "| Group | What it brings | Core | Extras |", "|---|---|---|---|"]
    for g, desc in pl.GROUPS.items():
        core = [k for k, v in visible.items() if v["group"] == g and v.get("tier", "core") == "core"]
        extra = [k for k, v in visible.items() if v["group"] == g and v.get("tier") == "extra"]
        out.append(f"| [`{g}`](#{_slug(g)}) | {esc(desc)} | {len(core)} | {len(extra)} |")
    out += ["", "```bash", "cloudseed platform list            # the catalog with what is installed on the current cluster",
            "cloudseed platform info basek8s    # every tool a group brings", "cloudseed platform plan basek8s    # what an install would do",
            "cloudseed platform install basek8s", "```", ""]
    for g, desc in pl.GROUPS.items():
        out += [f"## {g}", "", esc(desc), "", f"Install: `cloudseed platform install {g}` · Explain: `cloudseed explain group {g}`", ""]
        items = [k for k, v in visible.items() if v["group"] == g]
        items.sort(key=lambda k: (visible[k].get("tier", "core") != "core", list(visible).index(k)))
        out += ["| Item | What it is | Tier | Source | Targets | FIPS | Needs |", "|---|---|---|---|---|---|---|"]
        for k in items:
            s = visible[k]
            targets = ", ".join(s.get("only") or []) or "all"
            if s.get("arch"):
                targets += " (" + "/".join(s["arch"]) + " only)"
            out.append(f"| `{k}` | {esc(s['desc'])} | {s.get('tier', 'core')} | {code(_source(s))} | {esc(targets)} | "
                       f"{_FIPS_LABEL.get(s.get('fips'), 'no')} | {esc(_needs(s)) or '–'} |")
        if shared.get(g):
            out += ["", "Also installed with this group (members of other groups): "
                    + ", ".join(f"`{m}`" for m in shared[g]) + "."]
        out.append("")
    uis = getattr(pl, "UIS", {})
    if uis:
        out += ["## Web UIs", "", "`cloudseed platform ui` attaches an HTTPRoute on the shared private Gateway for every "
                "installed item below and prints its URL (`https://<item>.<domain>`) and login. Generated passwords live "
                "in `<workdir>/platform/secrets.json` (0600).", "", "| Item | Namespace / service | Login |", "|---|---|---|"]
        for k in sorted(uis):
            ns, svc, port = uis[k][0], uis[k][1], uis[k][2]
            login = uis[k][4] if len(uis[k]) > 4 else ""
            out.append(f"| `{k}` | {code(f'{ns}/{svc}:{port}')} | {esc(login) or '–'} |")
        out.append("")
    distro = getattr(pl, "PROVIDED_BY_DISTRO", {})
    rules = getattr(pl, "RULES", {})
    if distro or rules:
        out += ["## Step-overs and conflicts", ""]
        for k in sorted(distro):
            out.append(f"- `{k}` is built into {', '.join(distro[k])}: cloudseed skips it there.")
        for k in sorted(rules):
            r = rules[k]
            if r.get("conflicts"):
                out.append(f"- `{k}` conflicts with {', '.join(f'`{c}`' for c in r['conflicts'])}: the later one is "
                           "skipped unless `--force`.")
            if r.get("overlaps"):
                out.append(f"- `{k}` overlaps {', '.join(f'`{c}`' for c in r['overlaps'])}: both can run, the plan warns.")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


# ---------------------------------------------------------------- MCP
def _schema_type(p: dict) -> str:
    if "enum" in p:
        return " \\| ".join(f"`{e}`" for e in p["enum"])
    t = p.get("type", "any")
    if t == "array":
        return f"array of {p.get('items', {}).get('type', 'any')}"
    return str(t)


def page_mcp() -> str:
    from cloudseed import mcp
    tools = mcp.tool_list()
    resources = mcp.resource_list()
    templates = mcp.resource_templates() if hasattr(mcp, "resource_templates") else []
    prompts = mcp.prompt_list()
    out = [front("MCP tools reference", f"The cloudseed MCP server's {len(tools)} tools, resources and prompts: an MCP "
                 "server for cloud infrastructure for Claude Code, Claude Desktop, Codex, Cursor and VS Code."),
           "# MCP tools reference", "",
           f"`cloudseed setup mcp` turns cloudseed into a Model Context Protocol server with **{len(tools)} tools**, "
           f"**{len(resources) + len(templates)} resources** and **{len(prompts)} prompts**. Tools marked *confirm* "
           "change infrastructure, a host or a service (or can print secrets): the server refuses them unless the call "
           "carries `confirm=true`, which a client may only send after you agreed. See the [MCP guide](../guides/mcp.md).",
           "", generated_note("the MCP server's own tool list (`cloudseed/mcp.py`)"),
           "## Tools", "", "| Tool | Confirm | What it does |", "|---|---|---|"]
    for t in tools:
        ann = t.get("annotations") or {}
        if ann.get("destructiveHint"):
            need = "always" if "Needs confirm=true" in t["description"] else "some uses"
        else:
            need = "–"
        out.append(f"| [`{t['name']}`](#{_slug(t['name'])}) | {need} | {esc(t['description'])} |")
    out.append("")
    for t in tools:
        out += [f"### {t['name']}", "", esc(t["description"]), ""]
        props = (t.get("inputSchema") or {}).get("properties") or {}
        req = set((t.get("inputSchema") or {}).get("required") or [])
        if props:
            out += ["| Argument | Type | Required | Description |", "|---|---|---|---|"]
            for name in props:
                p = props[name] or {}
                out.append(f"| `{name}` | {_schema_type(p)} | {'yes' if name in req else ''} | {esc(p.get('description', ''))} |")
            out.append("")
    out += ["## Resources", "", "| URI | Description |", "|---|---|"]
    out += [f"| `{r['uri']}` | {esc(r.get('description', ''))} |" for r in resources]
    out += [f"| `{r['uriTemplate']}` | {esc(r.get('description', ''))} |" for r in templates]
    out += ["", "## Prompts", "", "| Prompt | Arguments | Description |", "|---|---|---|"]
    for p in prompts:
        args = ", ".join(f"`{a['name']}`" + ("" if a.get("required") else " (optional)") for a in p.get("arguments", []))
        out.append(f"| `{p['name']}` | {args or '–'} | {esc(p.get('description', ''))} |")
    out += ["", "## Clients cloudseed configures", "",
            "`cloudseed mcp connect <client>` writes the client's own config (`cloudseed mcp config` prints snippets for "
            "any other client).", "", "| Client | Name for `mcp connect` | Transports | Docs |", "|---|---|---|---|"]
    for key, c in mcp.CLIENTS.items():
        out.append(f"| {esc(c['display'])} | `{key}` | {', '.join(c.get('transports', ()))} | <{c['docs']}> |")
    out.append("")
    return "\n".join(out).rstrip() + "\n"


# ---------------------------------------------------------------- explain index
_KIND_ORDER = ("feature", "target", "command", "topic", "group", "item", "variable")
_KIND_TITLES = {"feature": "Features", "target": "Targets", "command": "Commands", "topic": "Topics",
                "group": "Platform groups", "item": "Platform items", "variable": "Setup variables"}


def _first_sentence(text: str, n: int = 160) -> str:
    text = " ".join(str(text).split())
    m = re.search(r"(?<=[a-z0-9)\]])[.!?](\s|$)", text)
    if m and m.end() <= n + 1:
        return text[: m.start() + 1]
    if len(text) <= n:
        return text
    return text[: n - 1].rsplit(" ", 1)[0].rstrip(" ,;:(-") + "…"


def _explain_names() -> list[dict]:
    """[{kind, name, summary, query}] - explain.names() when this cloudseed has it (the structured explain source),
    else the same set assembled from the data `cloudseed explain` reads."""
    from cloudseed import explain
    if hasattr(explain, "lookup") and hasattr(explain, "names"):
        structured = explain.names()
        if structured and all(isinstance(n, dict) for n in structured):
            return [dict(n) for n in structured]
    names: list[dict] = []
    for f, data in explain.FEATURES.items():
        names.append({"kind": "feature", "name": f, "summary": _first_sentence(data.get("what", "")), "query": f})
    for c in CLOUDS:
        names.append({"kind": "target", "name": c, "summary": f"What cloudseed setup {c} builds, with every variable and output.",
                      "query": f"target {c}"})
    rows = overview_rows()
    aliases: dict[str, list[str]] = {}
    for a, target in sorted(helpmod.ALIASES.items()):
        aliases.setdefault(target, []).append(a)
    for c in command_order():
        if c != "help":
            name = (aliases.get(c) or [c])[0] if c not in rows else c    # `managed` is explained as `databricks`
            names.append({"kind": "command", "name": name, "summary": _command_desc(c, rows, aliases),
                          "query": f"command {name}"})
    for t in _topic_order():
        names.append({"kind": "topic", "name": t, "summary": _topic_parts(t)[0], "query": f"topic {t}"})
    for g, desc in pl.GROUPS.items():
        names.append({"kind": "group", "name": g, "summary": desc, "query": f"group {g}"})
    for i, spec in pl.CATALOG.items():
        if not spec.get("hidden"):
            names.append({"kind": "item", "name": i, "summary": spec["desc"], "query": f"item {i}"})
    return names


def page_explain() -> str:
    names = _explain_names()
    by_kind: dict[str, list[dict]] = {}
    for n in names:
        by_kind.setdefault(n["kind"], []).append(n)
    total = len(names)
    out = [front("Explain index", "Everything cloudseed explain can explain - features, cloud targets, commands, topics, "
                 "platform groups and items and every setup variable - in the CLI, the web console and over MCP."),
           "# Explain index", "",
           f"`cloudseed explain` knows **{total} pages**. Each one is available the same way everywhere: "
           "`cloudseed explain <query>` in the terminal (`--json` for data), the **?** buttons and the Explain panel "
           "in the [web console](../guides/web-console.md), and `cloudseed_explain` / `cloudseed://explain/<query>` "
           "over [MCP](../guides/mcp.md). See the [explain guide](../guides/explain.md).", "",
           generated_note("the explain index (`cloudseed/explain.py`)")]
    out += ["| Kind | Pages |", "|---|---|"]
    for k in _KIND_ORDER + tuple(sorted(set(by_kind) - set(_KIND_ORDER))):
        if by_kind.get(k):
            out.append(f"| {_KIND_TITLES.get(k, k.capitalize())} | {len(by_kind[k])} |")
    out.append("")
    for k in _KIND_ORDER + tuple(sorted(set(by_kind) - set(_KIND_ORDER))):
        entries = by_kind.get(k)
        if not entries:
            continue
        out += [f"## {_KIND_TITLES.get(k, k.capitalize())}", ""]
        if k == "variable":
            per: dict[str, list[dict]] = {}
            for n in entries:
                per.setdefault(n["name"].split()[0], []).append(n)
            out += ["Every stack variable and setup input has its own page: `cloudseed explain variable <cloud> <name>` "
                    "(or `cloudseed explain <cloud> <name>`). The full tables live on the target pages:", "",
                    "| Target | Variables | Reference |", "|---|---|---|"]
            for c in sorted(per, key=lambda c: CLOUDS.index(c) if c in CLOUDS else 99):
                out.append(f"| {CLOUD_NAMES.get(c, c)} | {len(per[c])} | [{c}]({c}.md#stack-variables) |")
            out.append("")
            continue
        out += ["| Name | What it explains | Command |", "|---|---|---|"]
        for n in entries:
            out.append(f"| `{n['name']}` | {esc(n.get('summary', ''))} | `cloudseed explain {n.get('query') or n['name']}` |")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


# ---------------------------------------------------------------- skills
def page_skills() -> str:
    rows = []
    for p in sorted((ROOT / "skills").glob("*/SKILL.md")):
        text = p.read_text()
        name, desc = p.parent.name, ""
        if text.startswith("---"):
            fm = text[3:].split("---", 1)[0]
            m = re.search(r"^name:\s*(.+)$", fm, re.M)
            name = m.group(1).strip() if m else name
            m = re.search(r"^description:\s*(.+)$", fm, re.M)
            desc = m.group(1).strip() if m else ""
        rows.append((name, p.parent.name, desc))
    out = [front("Agent skills", f"The {len(rows)} Agent Skills (SKILL.md) bundled with cloudseed for Claude Code, Codex, "
                 "Gemini CLI and the built-in agent: operating manuals for driving cloud infrastructure safely."),
           "# Agent skills", "",
           f"cloudseed ships **{len(rows)} skills** in the Agent Skills format (`SKILL.md`) used by Claude Code, Codex, "
           "Gemini CLI and others. They are the operating manuals agents follow; the built-in agent reads them straight "
           "from cloudseed, and the MCP server serves them as `cloudseed://skills/<name>`.", "",
           generated_note("`skills/*/SKILL.md`"),
           "| Skill | Short name | When an agent uses it |", "|---|---|---|"]
    for name, folder, desc in rows:
        short = folder.replace("cloudseed-", "") if folder != "cloudseed" else "cloudseed"
        out.append(f"| [`{name}`]({REPO}/blob/main/skills/{folder}/SKILL.md) | `{short}` | {esc(desc)} |")
    out += ["", "```bash", "cloudseed skill list                          # the skills and where each agent keeps them",
            "cloudseed skill show aws                      # print one", "cloudseed skill install --agent claude         # copy them where Claude Code looks",
            "cloudseed skill install aws destroy --agent codex", "```", ""]
    return "\n".join(out).rstrip() + "\n"


# ---------------------------------------------------------------- index
def page_index(pages: dict[str, str]) -> str:
    out = [front("Reference", "cloudseed reference generated from the code: every CLI command, help topic, cloud "
                 "target variable and output, the platform catalog, MCP tools, the explain index and agent skills."),
           "# Reference", "",
           "Everything on these pages is generated from cloudseed itself by `scripts/gen-docs.py`, so it matches the "
           f"version you install (this build: **cloudseed {__version__}**).", "",
           "| Page | What is on it |", "|---|---|",
           "| [CLI commands](commands.md) | Every command with its synopsis, options and examples |",
           "| [Help topics](topics.md) | Quickstart, security model, state, environments, VMware, services, FIPS, troubleshooting |"]
    for c in CLOUDS:
        out.append(f"| [{CLOUD_NAMES[c]}]({c}.md) | What `setup {c}` builds, every variable and output |")
    out += ["| [Platform catalog](platform-catalog.md) | Every Helm / kustomize item, its group, version, targets and FIPS tier |",
            "| [MCP tools](mcp-tools.md) | Every MCP tool, its arguments, resources, prompts and clients |",
            "| [Explain index](explain-index.md) | Everything `cloudseed explain` can explain |",
            "| [Agent skills](skills.md) | The bundled SKILL.md operating manuals |", "",
            "Regenerate after changing the code:", "", "```bash", "python3 scripts/gen-docs.py          # rewrite what changed",
            "python3 scripts/gen-docs.py --check  # CI: fail when a page is out of date", "```", ""]
    return "\n".join(out).rstrip() + "\n"


def build() -> dict[str, str]:
    pages: dict[str, str] = {"commands.md": page_commands(), "topics.md": page_topics()}
    for c in CLOUDS:
        pages[f"{c}.md"] = page_target(c)
    pages["platform-catalog.md"] = page_platform()
    pages["mcp-tools.md"] = page_mcp()
    pages["explain-index.md"] = page_explain()
    pages["skills.md"] = page_skills()
    pages["index.md"] = page_index(pages)
    for name, text in pages.items():            # nothing from this machine or run may end up in a page
        assert _SCRATCH not in text and str(paths.HOME) not in text, f"{name}: a scratch path leaked"
        assert "\x1b[" not in text, f"{name}: ANSI escape"
    return dict(sorted(pages.items()))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="exit 1 when a page is missing or out of date; write nothing")
    ap.add_argument("--out", default=str(OUT), help="output directory (default: docs/reference)")
    args = ap.parse_args()
    out = Path(args.out)
    pages = build()
    stale = []
    for name, text in pages.items():
        p = out / name
        if p.exists() and p.read_text() == text:
            continue
        stale.append(name)
        if not args.check:
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(text)
    if args.check:
        if stale:
            print("out of date: " + ", ".join(stale) + "  (run: python3 scripts/gen-docs.py)", file=sys.stderr)
            return 1
        print(f"docs/reference is up to date ({len(pages)} pages)")
        return 0
    print(f"{len(stale)} of {len(pages)} pages written to {out}" if stale else f"all {len(pages)} pages already up to date")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    finally:
        import shutil
        shutil.rmtree(_SCRATCH, ignore_errors=True)
